apiVersion: v1
kind: Secret
metadata: 
  name: mongodb-secret
immutable: false
type: Opaque
data:
  password: cGFzc3dvcmQxMjM=

apiVersion: v1
kind: Secret
metadata: 
  name: AuthMongoDB-secret
immutable: false
type: Opaque
data:
  password: cXdlcnR5