apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-pvc
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 1Gi
    storageClassName: "MongoDB-Storage-AuthMS"
