apiVersion: v1
kind: Service
metadata:
  name: auth-ms
  labels:
    name: auth-ms
spec:
  type: LoadBalancer
  ports:
    - port: 3005
      targetPort: 4000
      protocol: TCP
  selector:
    name: auth-ms